[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "max-age=2592000000, must-revalidate"
        X-Content-Type-Options = "nosniff"
        Keep-Alive = "100"
        Connection = "keep-alive"
        Referrer-Policy = "no-referrer"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'none';
            script-src 'nonce-d2h5LXlvdS1kZWNvZGUtdGhpcw==' 'unsafe-inline' 'report-sample';
            manifest-src 'self';
            style-src 'nonce-c3Vzc3ktYmFrLWNoZWVzZWJ1cmdlcg==' 'nonce-am9lLW1hbWEtc3Vzc3ktYmFrYQ==' 'report-sample' https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            img-src https:;
            form-action 'self' https://www.sebastianelectric.org/submitted;
            font-src https://fonts.gstatic.com https://cdnjs.cloudflare.com;
            prefetch-src https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css https://www.freeiconspng.com/uploads/electric-icon-21.png;
            base-uri 'none';
            require-trusted-types-for 'script';
            report-uri https://maxsspot.report-uri.com/r/d/csp/enforce;
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
