[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "must-revalidate"
        Proxy-Authenticate = "Basic"
        Pragma = "must-revalidate"
        Access-Control-Allow-Origin = "https://www.freeiconspng.com/uploads/electric-icon-21.png"
        X-Permitted-Cross-Domain-Policies = "none"
        X-Content-Type-Options = "nosniff"
        Upgrade-Insecure-Requests = "1"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Download-Options = "noopen"
        Referrer-Policy = "no-referrer"
        Expect-CT = "enforce, max-age=3155760000, https://maxsspot.report-uri.com/r/d/ct/enforce"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Vary = "Upgrade-Insecure-Requests"
        Allow = "POST"
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        Content-Security-Policy = '''
            default-src 'self' https:;
            script-src 'self' 'unsafe-inline' https://www.googletagmanager.com/gtag/js?id=G-Y3M8QTBX56 www.clarity.ms/tag/ ;
            style-src 'self' 'nonce-jdJsid293iSj' 'nonce-dsajksadak2" 'nonce-fdaskSasdj312' 'strict-dynamic' https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            object-src 'none';
            base-uri 'none';
            frame-src 'none';
            child-src 'none';
            manifest-src 'none';
            media-src 'none';
            img-src https://s3-media0.fl.yelpcdn.com/bphoto/UaLg-7MI_zi72rRFfqdiWg/ls.jpg https://s3-media0.fl.yelpcdn.com/bphoto/k4Q_TpF8DKN4_Ao4xhFV4A/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/Obh_eW0eB6X6iGF_2BNVUw/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/slxhEPKDp4FjpOZc3Qu3YA/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/ZMKSdpG6Um7Qfs78pc6ANA/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/wuRFp6ktAJge85kgu09K-w/o.jpg https://www.freeiconspng.com/uploads/electric-icon-21.png;
            upgrade-insecure-requests;
            report-uri https://maxsspot.report-uri.com/r/d/csp/wizard;
        '''
        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
