[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "must-revalidate"
        Proxy-Authenticate = "Basic"
        Pragma = "must-revalidate"
        Origin = "www.sebastianelectric.org"
        X-Permitted-Cross-Domain-Policies = "none"
        X-Content-Type-Options = "nosniff"
        Upgrade-Insecure-Requests = "1"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Download-Options = "noopen"
        Referrer-Policy = "no-referrer"
        Expect-CT = "enforce, max-age=3155760000, https://maxsspot.report-uri.com/r/d/ct/enforce"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "unsafe-none"
        Vary = "Upgrade-Insecure-Requests"
        Allow = "POST"
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
