[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        Cache-Control = "must-revalidate"
        Accept-Encoding = "gzip"
        X-XSS-Protection = "1"
        Proxy-Authenticate = "Basic"
        Origin = "https://www.sebastianelectric.org"
        X-Permitted-Cross-Domain-Policies = "none"
        X-Content-Type-Options = "nosniff"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Download-Options = "noopen"
        Referrer-Policy = "no-referrer"
        Expect-CT = "enforce, max-age=3155760000, https://maxsspot.report-uri.com/r/d/ct/enforce"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "unsafe-none"
        Allow = "POST"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'self' https:;
            script-src 'nonce-d2h5LXlvdS1kZWNvZGUtdGhpcw==' 'report-sample';
            style-src 'nonce-c3Vzc3ktYmFrLWNoZWVzZWJ1cmdlcg==' 'nonce-am9lLW1hbWEtc3Vzc3ktYmFrYQ==' 'strict-dynamic' 'report-sample' https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap;
            img-src https://s3-media0.fl.yelpcdn.com/bphoto/UaLg-7MI_zi72rRFfqdiWg/ls.jpg https://s3-media0.fl.yelpcdn.com/bphoto/k4Q_TpF8DKN4_Ao4xhFV4A/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/Obh_eW0eB6X6iGF_2BNVUw/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/slxhEPKDp4FjpOZc3Qu3YA/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/ZMKSdpG6Um7Qfs78pc6ANA/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/wuRFp6ktAJge85kgu09K-w/o.jpg https://s3-media0.fl.yelpcdn.com/bphoto/-L2rwXjoP5vmrNZvz0Ld_w/o.jpg https://www.freeiconspng.com/uploads/electric-icon-21.png;
            manifest-src 'none';
            media-src 'none';
            object-src 'none';
            frame-src 'none';
            font-src *;
            frame-ancestors 'none';
            form-action www.sebastianelectric.org/submitted www.sebastianelectric.org www.sebastianelectric.org/pictures www.sebastianelectric.org/contact www.sebastianelectric.org/privacy-policy;
            worker-src 'none';
            prefetch-src https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css https://www.freeiconspng.com/uploads/electric-icon-21.png;
            connect-src https://www.google-analytics.com/g/collect?v=2&tid=G-Y3M8QTBX56&gtm=2oec10&_p=968591334&sr=360x640&ul=en-us&cid=1431003996.1638922577&_s=1&dl=https%3A%2F%2Fwww.sebastianelectric.org%2F&dt=Sebastian%20Electric%20LLC&sid=1638922576&sct=1&seg=0&en=page_view&_fv=1&_nsi=1&_ss=1;
            child-src 'none';
            base-uri 'none';
            upgrade-insecure-requests;
            report-uri https://maxsspot.report-uri.com/r/d/csp/enforce;
        '''

        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
